version: '3.8'

services:
  flask-api:
    build: .
    ports:
      - "10000:10000"
    volumes:
      - ./saved_data:/app/saved_data
      - ./scaler.pkl:/app/scaler.pkl:ro
      - ./features_info.pkl:/app/features_info.pkl:ro
      - ./model.h5:/app/model.h5:ro
      - ./model.keras:/app/model.keras:ro
      - ./saved_model:/app/saved_model:ro
    environment:
      - FLASK_ENV=production
      - PORT=10000
      - TF_CPP_MIN_LOG_LEVEL=2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3