version: '3.8'

services:
  flask-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./saved_data:/app/saved_data
      - ./my_best_model.h5:/app/my_best_model.h5
      - ./scaler.pkl:/app/scaler.pkl
      - ./feature_info.pkl:/app/feature_info.pkl
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3