version: '3.8'

services:
  flask-api:
    build: .
    ports:
      - "10000:10000"
    volumes:
      - ./saved_data:/app/saved_data
    environment:
      - FLASK_ENV=production
      - PORT=10000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3